In [4]:
import requests

def get_binance_price(symbol, timestamp):
    base_url = 'https://api.binance.com/api/v3/klines'
    interval = '1m'  # 1-minute interval
    limit = 1       # Only retrieve 1 data point

    # Convert timestamp to milliseconds
    timestamp_ms = timestamp * 1000

    # Construct the API endpoint URL
    url = f'{base_url}?symbol={symbol}&interval={interval}&limit={limit}&startTime={timestamp_ms}'

    try:
        response = requests.get(url)
        data = response.json()
#         Extract the closing price from the response
        price = float(data[0][4])  # Closing price is at index 4

        return price
    except requests.exceptions.RequestException as e:
        print('Error occurred:', e)

# Example usage: Get ETHUSDT price at a specific timestamp
symbol = 'ETHUSDT'
timestamp = 1630532698  # Replace with your desired timestamp

price = get_binance_price(symbol, timestamp)
print(f'ETHUSDT price at {timestamp}: {price}')

ETHUSDT price at 1630532698: 3754.75

In [13]:
import requests
import pandas as pd

def download_binance_data(symbol, start_time, end_time, interval):
    base_url = 'https://api.binance.com/api/v3/klines'
    limit = 1000  # Maximum limit per request

    data = []

    # Convert start and end times to milliseconds
    start_time_ms = int(start_time * 1000)
    end_time_ms = int(end_time * 1000)

    # Initial request to get the timestamp of the first data point
    url = f'{base_url}?symbol={symbol}&interval={interval}&limit=1&startTime={start_time_ms}&endTime={end_time_ms}'
    response = requests.get(url)
    initial_data = response.json()

    # Get the timestamp of the first data point
    timestamp = initial_data[0][0]

    # Download historical data in multiple requests (if needed)
    while timestamp < end_time_ms:
        url = f'{base_url}?symbol={symbol}&interval={interval}&limit={limit}&startTime={timestamp}&endTime={end_time_ms}'
        response = requests.get(url)
        batch_data = response.json()
        data.extend(batch_data)

        # Get the timestamp of the last data point in the batch
        timestamp = batch_data[-1][0]

    # Convert the data to a DataFrame
    df = pd.DataFrame(data, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume',
                                     'num_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore'])

    # Convert timestamp to datetime and set as index
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df.set_index('timestamp', inplace=True)

    # Convert numeric columns to appropriate data types
    numeric_cols = ['open', 'high', 'low', 'close', 'volume', 'quote_asset_volume', 'num_trades',
                    'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume']
    df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

    return df

# Example usage: Download ETHUSDT data for 1-hour granularity in 2023
symbol = 'ETHUSDT'
start_time = pd.Timestamp('2021-01-01').timestamp()
end_time = pd.Timestamp('2022-01-01').timestamp()
interval = '5m'

df = download_binance_data(symbol, start_time, end_time, interval)

# Print the downloaded data
# print(df.head())
df

,open,high,low,close,volume,close_time,quote_asset_volume,num_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
timestamp,,,,,,,,,,,
2021-01-01 00:00:00,736.42,739.00,735.94,736.89,2845.52132,1609459499999,2.098522e+06,1813,1941.92435,1.431829e+06,0
2021-01-01 00:05:00,737.06,737.11,732.42,732.80,2838.79347,1609459799999,2.086054e+06,2463,1441.44795,1.059184e+06,0
2021-01-01 00:10:00,732.87,734.08,730.03,731.14,4995.32144,1609460099999,3.655956e+06,3487,2438.66958,1.785006e+06,0
2021-01-01 00:15:00,731.14,732.22,730.46,731.50,2889.50420,1609460399999,2.113654e+06,1969,1703.04975,1.245908e+06,0
2021-01-01 00:20:00,731.57,731.89,729.33,731.70,2527.19773,1609460699999,1.846047e+06,2298,1201.22689,8.776467e+05,0
...,...,...,...,...,...,...,...,...,...,...,...
2021-12-31 23:40:00,3689.20,3695.78,3689.19,3693.29,1246.53900,1640994299999,4.600968e+06,1169,1048.40300,3.869414e+06,0
2021-12-31 23:45:00,3693.30,3693.51,3685.55,3686.59,319.53210,1640994599999,1.179021e+06,975,171.58760,6.330675e+05,0
2021-12-31 23:50:00,3686.59,3686.60,3677.81,3679.10,687.63080,1640994899999,2.531556e+06,1229,209.24260,7.705282e+05,0
2021-12-31 23:55:00,3679.36,3679.36,3672.22,3676.23,505.13270,1640995199999,1.857207e+06,1545,246.10540,9.048195e+05,0
2022-01-01 00:00:00,3676.22,3695.41,3676.22,3690.09,1363.45700,1640995499999,5.026545e+06,2516,697.45410,2.570994e+06,0